---
# tasks file for Dell-Networking.dellos-copy-config 
 - name: "Merge the config file to running configuration for OS9"
   dellos9_config:
      src: "{{ hostname }}.j2"
   when: (ansible_network_os == "dellos9" or ansible_net_os_name == "dellos9") 
#   notify: save config os9

 - name: "Merge the config file to running configuration for OS10"
   dellos10_config:
      src: "{{ hostname }}.j2"
   when: (ansible_network_os == "dellos10" or ansible_net_os_name == "dellos10") 
#   notify: save config os10
